project_id_env: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
export_only_approved: true
files:
  # JSON translation files
  - source: /i18n/en-US/**/*
    translation: /i18n/%locale%/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.md', '/**/current/*']
  # Docs avaota-sbc Markdown files
  - source: /docs/avaota-sbc/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/avaota-sbc/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.json']
  # Docs avaotaos Markdown files
  - source: /docs/linux-manual/avaotaos/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/linux-manual/avaotaos/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.json']
  # Docs avaotaos Markdown files
  - source: /docs/linux-manual/sdk-develop/kernel-dev/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/linux-manual/sdk-develop/kernel-dev/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.json']
  # Docs avaotaos Markdown files
  - source: /docs/linux-manual/sdk-develop/prepare-env/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/linux-manual/sdk-develop/prepare-env/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.json']