project_id: CROWDIN_PROJECT_ID
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
export_only_approved: true
files:
  # JSON translation files
  - source: /i18n/en-US/**/*
    translation: /i18n/%locale%/**/%original_file_name%
  # Docs avaota-sbc Markdown files
  - source: /docs/**/*
    translation: /i18n/%locale%/docusaurus-plugin-content-docs/current/**/%original_file_name%
    ignore: ['/**/*.jpg', '/**/*.png', '/**/*.jpeg', '/**/*.docx', '/**/*.json']
