# This is a basic workflow to help you get started with Actions

name: Sync Documents

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:
    name: Sync Documents
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create translate assets
        run: mkdir -p i18n/en-US/docusaurus-plugin-content-docs/current/

      - name: Copy assets to translate
        run: cp -ravf docs/* i18n/en-US/docusaurus-plugin-content-docs/current/

      - name: crowdin action
        uses: crowdin/github-action@v2
        with:
          config: "crowdin.yml"
          upload_sources: true
          upload_sources_args: "--delete-obsolete"
          download_translations: true
          export_only_approved: true
          create_pull_request: false
          push_translations: false
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_TOKEN_KEY }}

      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: package-lock.json

      - name: install nodejs package
        run: npm install

      - name: set BUILDCOMMIT date
        run: sed -i "s/BUILDCOMMIT/$(date)/g" docusaurus.config.js

      - name: bake doc
        run: npm run build

      - name: 📂 Sync Files
        uses: SamKirkland/web-deploy@v1
        continue-on-error: true
        with:
          target-server: ${{ secrets.FTP_SERVER_IP }}
          remote-user: ${{ secrets.FTP_SERVER_USERNAME }}
          private-ssh-key: ${{ secrets.FTP_SERVER_PASSWD }}
          destination-path: /www/wwwroot/docs.avaota.fun/
          source-path: ${{ github.workspace }}/build/
          rsync-options: --archive --compress --delete-after --exclude=.git* --exclude=.well-known/ --exclude=.user.ini --exclude=.htaccess --exclude=.git/ --exclude=.gitignore --no-times

